### PR TITLE
Add dagger2

### PR DESCRIPTION
**Pull request by yoavgray**
@dbautist @nirvanalab @jjc3737 

Added Dagger 2 in the most simple way possible. Later I'll add some api request to the movie detail activity to show the necessity of dependency injection. This PR is opened against `minimize-app-code` branch, so please accept that one before accepting this one.

Also, please take a look at: https://hackmd.io/KYdhDYGMCYCMEYC0AOa8CsiAsAzAJtIgIawCckies6ew+40w8WQA?both 
again and feel free to correct grammar/typos or style.

Thanks!

### CODE REVIEW

**Comment by jjc3737** [comment]
@yoavgray can we have this just as a separate branch so we can have the skeleton app on master

**Comment by jjc3737** [comment]
my mvp can be built on top of this branch into another branch

**Comment by jjc3737** [comment]
:+1:

**Comment by yoavgray** [comment]
I'm closing this PR and leaving it on this branch.

**Pull request closed without merging**
